# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('tv', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('p_type', models.CharField(choices=[('T', 'Townhouse'), ('C', 'Condominium'), ('A', 'Apartment'), ('H', 'House')], max_length=1)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
                ('air_id', models.IntegerField()),
                ('title', models.TextField()),
                ('location', models.TextField()),
                ('pic_url', models.TextField()),
            ],
        ),
    ]
